global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: stratum-backend
    metrics_path: /metrics
    static_configs:
      - targets: ['backend:4001']
  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']
